name: Or Condition
on: push
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Run for Ammarkhan96
      if: github.actor == 'Ammar' || github.actor == 'Ammarkhan96'
      run: echo "It is triggered by either Ammar or Ammarkhan96
